#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "EXTREMEPRO" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlYW1leHRyZW1lcHJvL2V4dHJlbWVwcm91c2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA=='" | base64 -d
    elif [[ $UPSTREAM_REPO == "DEV" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlYW1leHRyZW1lcHJvL2V4dHJlbWVwcm91c2VyYm90L2FyY2hpdmUvZGV2LnppcA=='" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL3RlYW1leHRyZW1lcHJvL2V4dHJlbWVwcm91c2VyYm90L2FyY2hpdmUvbWFzdGVyLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="extremeprouserbot.zip"
    echo "  Downloading USERBOT ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  UNZIPPING Data ..."
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $CATPATH
    echo "    Read Legal Notice    "
    echo "
                        Copyright Team ExtremePro 2021-2022
    "

    echo "
    'Setting up our bot
    "
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "    Starting Our Bot Now    "
    python3 -m Extre
}

_set_bot
clear_screen()
