#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "ULTROID" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1VbHRyb2lkL1VsdHJvaWQvYXJjaGl2ZS9tYWluLnppcA=='" | base64 -d
    elif [[ $UPSTREAM_REPO == "DEV" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1VbHRyb2lkL1VsdHJvaWQvYXJjaGl2ZS9tYWluLnppcA=='" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1VbHRyb2lkL1VsdHJvaWQvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="ultroid.zip"
    echo "  Setting Up ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  UNZIPPING Data ..."
    CATPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $CATPATH
    echo "    Read Legal Notice    "
    echo "
                         
        +-+ +-+ +-+ +-+ +-+ +-+ +-+
        |U| |L| |T| |R| |O| |I| |D|
        +-+ +-+ +-+ +-+ +-+ +-+ +-+
 
 
      Visit @TheUltroid for updates!!
    "

    echo "
    'Team Ultroid
    "
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    echo "    Starting Our Bot Now    "
    python3 -m pyUltroid
}

_set_bot
